# Enhanced Radio Server Configuration

# Server Settings
server:
  host: "0.0.0.0"
  port: 5000
  debug: true

# Content Generation
content:
  openrouter_api_key: null  # Set via environment variable OPENROUTER_API_KEY
  max_tokens: 300
  temperature: 0.7
  model: "moonshotai/kimi-k2-0905"

# Scheduler Settings
scheduler:
  ad_interval: 120          # Generate ad every 2 minutes
  conversation_interval: 300 # Generate conversation every 5 minutes
  auto_start: false         # Start scheduler automatically

# Voice Settings
voice:
  tts_device: "auto"        # "auto", "cuda", or "cpu"
  default_voice: "host"
  radio_effect_strength: 0.8

# File Paths
paths:
  content_dir: "content"
  temp_audio_dir: "temp_audio"
  generated_content_dir: "generated_content"
  logs_dir: "logs"
  voices_dir: "voices"

# Audio Settings
audio:
  sample_rate: 24000
  cleanup_interval: 1800    # Clean temp files every 30 minutes
  max_file_age: 3600       # Delete files older than 1 hour

# Logging
logging:
  level: "INFO"
  console: true
  file: true
  max_log_files: 10

# Default Voice Mappings (fallback if personality files don't specify)
default_voice_mappings:
  main_host:
    voice_file: "voices/host.wav"
    exaggeration: 1.2
    temperature: 0.8
    cfg_weight: 0.4
    radio_effect: "vintage_radio"

  frequent_caller:
    voice_file: "voices/frequent_caller.wav"
    exaggeration: 1.3
    temperature: 0.9
    cfg_weight: 0.45
    radio_effect: "phone_call"

  expert_guest:
    voice_file: "voices/expert_guest.wav"
    exaggeration: 1.1
    temperature: 0.7
    cfg_weight: 0.35
    radio_effect: "super_muffled"

# GUI Settings
gui:
  window_title: "Enhanced Radio Server Control"
  window_size: [800, 600]
  theme: "default"
  auto_refresh_interval: 2000  # milliseconds